language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw

script: "mvn clean clover:setup test clover:aggregate clover:clover"

after_success:
  - bash <(curl -s https://codecov.io/bash)